error404/error404/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

error404/polls/urls.py
from django.urls import path

from . import views
from . import views2
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
 
    path("consultar/<int:question_id>/", views2.detail, name="detail2"),
]

error404/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

error404/polls/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Question

def index(request):
    list_question = Question.objects.all()
    return render(request, "polls/index.html", {"list_question": list_question})

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})

error404/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {{ question.question_text }}
<ul>
{% for choice in question.choice_set.all %}<!-- question. es la ForeignKey y con question.choice_set.all traemos
todos los question_id que hay en Choice, question.choice_set.all choice porque la tabla se llama Choice
-->
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
    
</body>
</html>

error404/templates/polls/detail2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document2</title>
</head>
<body>
    {{ question.question_text }}
    <ul>
        {% for choice in question.choice_set.all %}<!-- question. es la ForeignKey y con question.choice_set.all traemos
            todos los question_id que hay en Choice, question.choice_set.all choice porque la tabla se llama Choice
            -->
        <li>{{ choice.votes }}</li>
    {% endfor %}
    </ul>
</body>
</html>

error404/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% if list_question %}
    <ul>
    {% for q in list_question %}
        <!-- es lo mismo <li><a href="/polls/{{ q.id }}/">{{ q.question_text }}</a></li>  -->
        <li><a href="{% url 'detail' q.id %}">{{ q.question_text }}Ver respuestas</a></li>
        <li><a href="{% url 'detail2' q.id %}">{{ q.question_text }}Ver votos</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    
</body>
</html>